# Generated by Django 5.2.5 on 2025-08-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
